/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <pthread.h>
#include <unistd.h>
#include "constants.h"

struct ticket_t
{
	int num_queue;
	char res;
	int ind;
};
typedef struct ticket_t ticket_t;

int choosing[max_client] = { 0 };
int num[max_client] = { 0 };
char sym = 'a';
int num_clnt = 0;

void* get_ticket(void *arg)
{
	ticket_t *ticket = (ticket_t *)arg;
	int i = num_clnt++;
	ticket->ind = i;

	choosing[i] = 1;
	int max = 0;
	for (int j = 0; j < max_client; j++)
	{
		if (num[j] > max)
		{
			max = num[j];
		}
	}
	num[i] = max + 1;
	ticket->num_queue = num[i];
	choosing[i] = 0;
	// return 0;
}

void* get_symbol_bakery(void *arg)
{
	ticket_t *ticket = arg;
	int i = ticket->ind;

	for (int j = 0; j < max_client; j++) 
	{
		while (choosing[j]){};
		while ((num[j] > 0) && (num[j] < num[i] || 
		(num[j] == num[i] && j < i))){};
	}

	ticket->res = sym++;
	num[i] = 0;
	// return 0;
}

struct bakery_t *
bakery_proc_1_svc(struct bakery_t *argp, struct svc_req *rqstp)
{
	static struct bakery_t  result;
	pthread_t thread;
	ticket_t ticket;

	if (argp->op == get_number)
	{
		pthread_create(&thread, NULL, get_ticket, &ticket);
		pthread_join(thread, NULL);
		result.num = ticket.num_queue;
		result.op = ticket.ind;
	}
	else if (argp->op == get_symbol)
	{
		ticket.ind = argp->num;
		pthread_create(&thread, NULL, get_symbol_bakery, &ticket);
		pthread_join(thread, NULL);
		result.result = ticket.res;
	}

	return &result;
}
