/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <pthread.h>
#include <stdbool.h>
#include <unistd.h>
#include "bakery.h"


typedef struct target
{
	int num; // очередь
	char res;
	int id;  
} target_t;

int choosing[max_client] = { 0 };
int number[max_client] = { 0 };
char sym = 'a';
int num = 0;

void *
get_targ(void *arg)
{
	target_t *targ = arg;
	int i = num++;
	targ->id = i;
	choosing[i] = 1;
	int max = 0;

	for (int j = 0; j < max_client; j++)
	{
		if (number[j] > max)
		{
			max = number[j];
		}
	}

	number[i] = max + 1;
	targ->num = number[i];
	choosing[i] = 0;
}

void *
bakery(void *arg)
{
	target_t *targ = arg;
	int i = targ->id;

	for (int j = 0; j < max_client; j++) 
	{
		while (choosing[j]){};
		while ((number[j] > 0) && (number[j] < number[i] || 
		(number[j] == number[i] && j < i))){};
	}
	
	targ->res = sym++;
	number[i] = 0;

	return 0;
}

struct BAKERY *
bakery_proc_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;
	pthread_t thread;
	target_t tres;
	switch (argp->op)
	{
		case get_number:
		{
			pthread_create(&thread, NULL, get_targ, &tres);
			pthread_join(thread, NULL);
			result.pid = argp->pid;
			result.num = tres.num;
			result.op = tres.id;
			break;
		}
		case get_symbol:	
		{
			tres.id = argp->num;
			pthread_create(&thread, NULL, bakery, &tres);
			pthread_join(thread, NULL);
			result.pid = argp->pid;
			result.result = tres.res;
			result.op = tres.id;
			break;
		}
		default:
			break;

	}

	return &result;
}
