/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "bakery.h"

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	struct BAKERY *response;
	struct BAKERY bakery_proc_1_arg;
	
	clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");

	if (clnt == NULL) 
	{
		clnt_pcreateerror(host);
		exit(1);
	}

	srand(time(NULL));
	int interval = rand() % 4 + 1;
	sleep(interval);

	bakery_proc_1_arg.op = get_number;
	response = bakery_proc_1(&bakery_proc_1_arg, clnt);

	printf("\nClient pid = %d queue %d \n", getpid(), response->num);
	
	if (response == (struct BAKERY *) NULL) 
	{
		clnt_perror(clnt, "bakery_proc_1 failed");
	}

	sleep(interval);
	
	bakery_proc_1_arg.op = get_symbol; 
	bakery_proc_1_arg.num = response->op;
	bakery_proc_1_arg.pid = getpid();
	response = bakery_proc_1(&bakery_proc_1_arg, clnt);

	if (response == (struct BAKERY *) NULL) 
	{
		clnt_perror(clnt, "bakery_proc_1 failed");
	}

	printf("%d Symbol get %c (sleep = %d)\n\\n", response->pid, response->result, interval);
	clnt_destroy(clnt);
}

int
main (int argc, char *argv[])
{
	setbuf(stdin, NULL);
	char *host;

	if (argc < 2) 
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	printf("\n");
	bakery_prog_1(host);
	exit(0);
}
