all:
	gcc task_01.c -o bin/task_01.out
	gcc task_02.c -o bin/task_02.out
	gcc task_03.c -o bin/task_03.out
	gcc task_04.c -o bin/task_04.out
	gcc task_05.c -o bin/task_05.out
	
	gcc prog1.c -o bin/prog1.out
	gcc prog2.c -lm -o bin/prog2.out